FROM python:slim-stretch

RUN apt-get update && apt-get install -y --no-install-recommends libopencv-dev && \
    pip3 install opencv-python --no-cache-dir && \
    apt-get remove -y python3-pip && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip3 install opencv-python --no-cache-dir

RUN mkdir /iexec_in /iexec_out

COPY object_detector.py /object_detector.py

ENTRYPOINT python3 /object_detector.py